---
abstract: 'Extend your attribute interfaces for Mouse'
author:
  - 'Goro Fuji (gfx) <gfuji(at)cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.29
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.93'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MouseX::NativeTraits
name: MouseX-NativeTraits
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Mouse: 0.5002
  perl: 5.6.2
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/Perl-MouseX-NativeTraits.git
version: 0.001_01
